# yaml-language-server: $schema=./node_modules/@sargonpiraev/eslint-config/build/schemas/project__workflow-on-push-main.json
name: on-push-main

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: sargonpiraev/shared/.github/workflows/on-push-main.yml@main
    secrets: inherit
